version: '3.8'

services:
  beerlocal-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:12-alpine
    container_name: beerlocal-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - MONGO_URI=$MONGO_URI
      - MAILGUN_DOMAIN=$MAILGUN_DOMAIN
      - MAILGUN_API_KEY=$MAILGUN_API_KEY